apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: shai
  labels:
    app: helloworld
spec:
  selector:
    app: helloworld
  type: LoadBalancer
  ports:
  - name: web
    port: 8080
